services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: api-sv
    environment:
      - CLIENT_URL_ORIGIN=http://localhost
      - NODE_ENV='development'
      - PORT=4000
    networks:
      - super-card-net
    expose:
      - 4000
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    networks:
      - super-card-net
    volumes:
      - ../fontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  super-card-net:
    driver: bridge
