services:
  api_prod:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    container_name: api-sv-prod
    environment:
      - CLIENT_URL_ORIGIN=https://super-card.online
      - NODE_ENV='production'
      - PORT=4000
    networks:
      - super-card-net
    expose:
      - 4000
  nginx_prod:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    networks:
      - super-card-net
    volumes:
      - ../fontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  super-card-net:
    driver: bridge
